# Generated by Django 4.1.7 on 2023-03-26 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_problem"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="problem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
