# Generated by Django 4.1.7 on 2023-03-25 05:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("answer", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Problem",
        ),
    ]
